#!/usr/bin/env zsh

SCRIPT_PATH=$(dirname $(realpath $0))

cd ${SCRIPT_PATH}
echo "Running cmake"
/opt/homebrew/bin/cmake --build . --config Release --verbose
rm -rf $1

echo "Building $1"
xcodebuild -create-xcframework -library libCube.a -headers include -output $1

